# After this file is created, we can conda env create
name: py385_cb

channels:
    - defaults

dependencies:
    - python==3.8.5  # The first line should always be python version
    - pip
    - pillow
    - pip:
          - pipdeptree # or conda install -c conda-forge pipdeptree
